-- harpoon by the name is: ThePrimeagen
return {
	"ThePrimeagen/harpoon",
	config = function()
		local mark = require("harpoon.mark")
		local ui = require("harpoon.ui")

		vim.keymap.set("n", "<leader>ha", function()
			mark.add_file()
			ui.toggle_quick_menu()
		end)
		vim.keymap.set("n", "<leader>a", ui.toggle_quick_menu)
		vim.keymap.set("n", "<leader>he", ui.toggle_quick_menu)
		vim.keymap.set("n", "<leader>hi", ui.toggle_quick_menu)
		vim.keymap.set("n", "<c-j>", function()
			ui.nav_file(1)
		end)
		vim.keymap.set("n", "<c-k>", function()
			ui.nav_file(2)
		end)
		vim.keymap.set("n", "<c-l>", function()
			ui.nav_file(3)
		end)
		-- vim.keymap.set("n", "<c-m>", function()
		-- 	ui.nav_file(4)
		-- end)
		-- vim.keymap.set("n", "<c-,>", function()
		-- 	ui.nav_file(5)
		-- end)
		-- vim.keymap.set("n", "<c-.>", function()
		-- 	ui.nav_file(6)
		-- end)
		vim.keymap.set("n", "<leader>1", function()
			ui.nav_file(1)
		end)
		vim.keymap.set("n", "<leader>2", function()
			ui.nav_file(2)
		end)
		vim.keymap.set("n", "<leader>3", function()
			ui.nav_file(3)
		end)
		vim.keymap.set("n", "<leader>4", function()
			ui.nav_file(4)
		end)
		vim.keymap.set("n", "<leader>5", function()
			ui.nav_file(5)
		end)
		vim.keymap.set("n", "<leader>6", function()
			ui.nav_file(6)
		end)
		--
		--
		--vim.keymap.set('n', '<c-;>', function() ui.nav_file(4) end)
		-- vim.keymap.set('n', ';', function() ui.nav_next() end)
		-- vim.keymap.set('n', ',', function() ui.nav_prev() end)
	end,
}
